### ISSUE TITLE
repsheet-3.1.0-1.x86_64 and libhiredis.so.0.10 vs hiredis 0.13 ?

### ISSUE THREAD

**Issue by centminmod** [repsheet/repsheet-nginx#21]
On CentOS 7.1 64bit, tried installing repsheet-3.1.0-1.x86_64.rpm but get error

    error: Failed dependencies:
            libhiredis.so.0.10()(64bit) is needed by repsheet-3.1.0-1.x86_64

But from https://github.com/repsheet/repsheet-nginx, it says requires hiredis 0.13 or higher ? So that's what I installed - I had to build my own hiredis 0.13 RPMs for CentOS 6/7.

    rpm -qa | grep hiredis
    hiredis-0.13.1-1.el7.centos.x86_64
    hiredis-devel-0.13.1-1.el7.centos.x86_64

Contents of hiredis CentOS 7.x

    rpm -ql hiredis
    /usr/lib64/libhiredis.so.0
    /usr/lib64/libhiredis.so.0.13
    /usr/share/doc/hiredis-0.13.1
    /usr/share/doc/hiredis-0.13.1/COPYING

Contents of hiredis-devel CentOS 7.x

    rpm -ql hiredis-devel
    /usr/include/hiredis
    /usr/include/hiredis/adapters
    /usr/include/hiredis/adapters/ae.h
    /usr/include/hiredis/adapters/glib.h
    /usr/include/hiredis/adapters/libev.h
    /usr/include/hiredis/adapters/libevent.h
    /usr/include/hiredis/adapters/libuv.h
    /usr/include/hiredis/async.h
    /usr/include/hiredis/hiredis.h
    /usr/include/hiredis/read.h
    /usr/include/hiredis/sds.h
    /usr/lib64/libhiredis.so
    /usr/lib64/pkgconfig/hiredis.pc
    /usr/share/doc/hiredis-devel-0.13.1
    /usr/share/doc/hiredis-devel-0.13.1/CHANGELOG.md
    /usr/share/doc/hiredis-devel-0.13.1/README.md

Or is it for repsheet-3.1.0-1.x86_64.rpm, hiredis 0.10 is enough ?

**Comment by abedra** [comment]
It needs to be hiredis 0.13 or higher. There were some changes that were made to support connection read timeouts and this version is necessary for that to work properly.
