### ISSUE TITLE
X_repsheet_header is back to being "true" when DB key is set

### ISSUE THREAD

**Issue by davidhanley** [repsheet/repsheet-nginx#41]
The new master seems to have reintroduced the behavior of a marked actor triggering X_Repsheet="true", regardless of the value of the key in the DB.  So, for example:

set 127.0.0.1:repsheet:ip:marked '"bemod"'

then the headers ( determined by hitting the sinatra app ) 

"HTTP_X_REPSHEET"=>"true"

**Comment by abedra** [comment]
Looks like this happened in #38. It wouldn't be too difficult to add this back in though.
